<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>404 ERROR</title>
<style type="text/css">
body{font-size:12px}
.error{
width:80%;
height:120px;
line-height:120px;
text-align:center;
margin:20px auto;
padding:2px;
border:dashed 1px #DBD9D0;
font-family:'Arial';
background-color:#FAFADF
}
</style>
</head>
<body>
<div class="error">
404 Error,Sorry Page Not Found!
</div>
</body>
</html>