<?php foreach ($this->get_styles() as $value):?>
<link rel="stylesheet" rev="stylesheet" href="<?=$this->get_style_url($value)?>"/>
<?php endforeach;?>
<?php foreach ($this->get_javascripts() as $value):?>
<script type="text/javascript" src="<?=$this->get_javascript_url($value)?>"></script>
<?php endforeach;?>

<?php if($this->is_boundable_resource_enabled()):?>
    <?php if($this->get_boundable_styles()):?>
        <link rel="stylesheet" rev="stylesheet" href="<?=$this->get_boundable_styles_url()?>" />
    <?php endif;?>
    <?php if($this->get_boundable_javascripts()):?>
    <script type="text/javascript" src="<?=$this->get_boundable_javascripts_url()?>"></script>
    <?php endif;?>
<?php else:?>
    <?php foreach ($this->get_boundable_styles() as $value):?>
    <link rel="stylesheet" rev="stylesheet" href="<?=$this->get_style_url($value)?>"/>
    <?php endforeach;?>
    <?php foreach ($this->get_boundable_javascripts() as $value):?>
    <script type="text/javascript" src="<?=$this->get_javascript_url($value)?>"></script>
    <?php endforeach;?>
<?php endif;?>