<?php foreach ($this->get_javascripts() as $value):?>
    <script type="text/javascript" src="<?php echo $this->get_javascript_url($value); ?>"></script>
<?php endforeach;?>
<?php if($this->is_boundable_resource_enabled()):?>
    <?php if($this->get_boundable_javascripts()):?>
        <script type="text/javascript" src="<?php echo $this->get_boundable_javascripts_url(); ?>"></script>
    <?php endif;?>
<?php else:?>
    <?php foreach ($this->get_boundable_javascripts() as $value): ?>
    <script type="text/javascript" src="<?php echo $this->get_javascript_url($value); ?>"></script>
    <?php endforeach; ?>
<?php endif;?>

<?php if($this->get_script_blocks()):?>
<script type="text/javascript">
<?php
    $blocks='';
    foreach ($this->get_script_blocks() as $block){
        $blocks.=preg_replace('/^\s*<script[^>]*>(.*)<\/script>\s*$/ims', '$1', $block);
    }
    //判断是否开启js压缩
    $enable_minjs=$this->zhf->get_config('enable_minjs','resource');
    if($enable_minjs){
            if(defined('SYS_PATH')){
                require_once SYS_PATH.'lib/JSMin.php';;
            }
            else{
                zhf_require_file('JSMin.php');
            }
            $blocks=JSMin::minify($blocks);
    }
    echo $blocks;
?>
</script>
<?php endif;?>
